from __future__ import annotations

from pathlib import Path

import app.core.orchestrator as orchestrator_module
from app.core.logger import append_event as real_append_event
from app.core.orchestrator import Orchestrator
from app.core.scope import ScopeCheckResult
from app.schemas.tasks import Task
from app.tools.tool_cards import ToolArgument, ToolCard, ToolRegistration


class DummyAether:
    def __init__(self, action: str = "run_nmap") -> None:
        self.action = action

    def classify_task(self, objective: str) -> str:
        return "recon"

    def plan(self, task: Task) -> dict:
        return {
            "agent": "AETHER",
            "action": self.action,
            "reason": "test plan",
        }


class DummyScribe:
    def __init__(self, report_text: str = "# Test Report\n\nGenerated by test.") -> None:
        self.report_text = report_text

    def generate_markdown_report(self, session_id: str, objective: str, parsed_output: dict) -> str:
        return self.report_text


class DummyWatcher:
    def process(self, session_id: str, parsed_output: dict, previous_memory: dict | None = None) -> dict:
        return {
            "agent": "WATCHER",
            "observations": ["Host: test.local"],
            "unresolved": [],
            "suggestions": ["run_http_probe"],
            "tags": ["service:http"],
            "summary": "HTTP detected.",
            "priority": "medium",
        }


class DummyTool:
    def __init__(self, result: dict) -> None:
        self.result = result
        self.called_with: str | None = None

    def run(self, target: str) -> dict:
        self.called_with = target
        return self.result


def _session_path_factory(tmp_path: Path):
    def _get_session_path(session_id: str) -> Path:
        path = tmp_path / session_id
        path.mkdir(parents=True, exist_ok=True)
        return path

    return _get_session_path


def _tool_entry(tool) -> ToolRegistration:
    return ToolRegistration(
        card=ToolCard(
            key="run_nmap",
            display_name="Nmap Service Scan",
            summary="Test tool card.",
            approval_class="explicit_approval",
            scope_rule="single_target",
            allowed_categories=("recon",),
            arguments=(
                ToolArgument(
                    name="target",
                    kind="target",
                    required=True,
                    description="Single target",
                ),
            ),
            artifacts=("nmap_stdout.txt", "nmap_stderr.txt"),
            common_followups=("run_http_probe",),
            failure_modes=("nonzero_returncode",),
            operator_notes="Test card.",
        ),
        tool=tool,
        parser=orchestrator_module.parse_nmap_output,
        stores_findings=True,
        generates_report=True,
        uses_watcher=True,
    )


def _patch_common(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setattr(orchestrator_module, "get_session_path", _session_path_factory(tmp_path))
    monkeypatch.setattr(orchestrator_module, "save_task", lambda task: None)
    monkeypatch.setattr(orchestrator_module, "save_tool_run", lambda **kwargs: 1)
    monkeypatch.setattr(
        orchestrator_module,
        "save_findings",
        lambda session_id, parsed_output, task_id=None, tool_run_id=None: None,
    )
    monkeypatch.setattr(orchestrator_module, "save_session_memory", lambda session_id, data: None)
    monkeypatch.setattr(orchestrator_module, "get_session_memory", lambda session_id: None)
    monkeypatch.setattr(orchestrator_module, "append_event", real_append_event)


def test_orchestrator_blocks_without_approval(monkeypatch, tmp_path):
    _patch_common(monkeypatch, tmp_path)

    orchestrator = Orchestrator()
    orchestrator.aether = DummyAether(action="run_nmap")

    scope_called = {"value": False}
    tool = DummyTool(
        {
            "tool": "nmap",
            "command": "nmap -Pn -sV 10.0.0.1",
            "stdout": "",
            "stderr": "",
            "returncode": 0,
        }
    )

    def fake_validate_single_target(target: str | None) -> ScopeCheckResult:
        scope_called["value"] = True
        return ScopeCheckResult(True, "10.0.0.1", "Valid single IP target.")

    monkeypatch.setattr(orchestrator_module, "validate_single_target", fake_validate_single_target)
    monkeypatch.setitem(orchestrator_module.TOOL_REGISTRY, "run_nmap", _tool_entry(tool))

    result = orchestrator.run_task(
        Task(
            session_id="session-no-approval",
            objective="scan 10.0.0.1",
            target="10.0.0.1",
            approved=False,
        )
    )

    assert result["status"] == "blocked"
    assert result["message"] == "Task requires explicit approval before execution."
    assert result["tool_card"]["key"] == "run_nmap"
    assert scope_called["value"] is False
    assert tool.called_with is None


def test_orchestrator_blocks_invalid_scope(monkeypatch, tmp_path):
    _patch_common(monkeypatch, tmp_path)

    orchestrator = Orchestrator()
    orchestrator.aether = DummyAether(action="run_nmap")

    tool = DummyTool(
        {
            "tool": "nmap",
            "command": "nmap -Pn -sV invalid",
            "stdout": "",
            "stderr": "",
            "returncode": 0,
        }
    )

    monkeypatch.setattr(
        orchestrator_module,
        "validate_single_target",
        lambda target: ScopeCheckResult(False, None, "Target must be a single IPv4/IPv6 address or hostname."),
    )
    monkeypatch.setitem(orchestrator_module.TOOL_REGISTRY, "run_nmap", _tool_entry(tool))

    result = orchestrator.run_task(
        Task(
            session_id="session-invalid-scope",
            objective="scan invalid target",
            target="https://bad/target",
            approved=True,
        )
    )

    assert result["status"] == "blocked"
    assert result["message"] == "Target must be a single IPv4/IPv6 address or hostname."
    assert result["tool_card"]["key"] == "run_nmap"
    assert tool.called_with is None


def test_orchestrator_saves_report_and_artifacts_on_success(monkeypatch, tmp_path):
    _patch_common(monkeypatch, tmp_path)

    orchestrator = Orchestrator()
    orchestrator.aether = DummyAether(action="run_nmap")
    orchestrator.scribe = DummyScribe(report_text="# Success Report\n\nAll good.")
    orchestrator.watcher = DummyWatcher()

    saved_memory: list[tuple[str, dict]] = []
    saved_findings: list[dict] = []
    saved_tool_runs: list[dict] = []

    monkeypatch.setattr(
        orchestrator_module,
        "validate_single_target",
        lambda target: ScopeCheckResult(True, "test.local", "Valid hostname target."),
    )
    monkeypatch.setattr(
        orchestrator_module,
        "parse_nmap_output",
        lambda output: {
            "host": "test.local",
            "host_status": "up",
            "filtered_summary": None,
            "closed_summary": None,
            "open_ports": [80],
            "services": ["http"],
            "port_details": [
                {
                    "port": 80,
                    "protocol": "tcp",
                    "state": "open",
                    "service": "http",
                    "version": "nginx 1.24.0",
                }
            ],
            "os_hint": "Linux",
            "scan_protocols_seen": ["tcp"],
            "all_port_states": {"open": 1},
            "evidence_count": 1,
        },
    )

    def fake_save_findings(session_id, parsed_output, task_id=None, tool_run_id=None):
        saved_findings.append(
            {
                "session_id": session_id,
                "parsed_output": parsed_output,
                "task_id": task_id,
                "tool_run_id": tool_run_id,
            }
        )

    def fake_save_tool_run(**kwargs):
        saved_tool_runs.append(kwargs)
        return 99

    monkeypatch.setattr(
        orchestrator_module,
        "save_session_memory",
        lambda session_id, data: saved_memory.append((session_id, data)),
    )
    monkeypatch.setattr(orchestrator_module, "save_tool_run", fake_save_tool_run)
    monkeypatch.setattr(orchestrator_module, "save_findings", fake_save_findings)

    tool = DummyTool(
        {
            "tool": "nmap",
            "command": "nmap -Pn -sV test.local",
            "stdout": "Nmap scan report for test.local\nHost is up.\n80/tcp open http nginx 1.24.0\n",
            "stderr": "",
            "returncode": 0,
        }
    )
    monkeypatch.setitem(orchestrator_module.TOOL_REGISTRY, "run_nmap", _tool_entry(tool))

    session_id = "session-success"
    task = Task(
        session_id=session_id,
        objective="scan test.local",
        target="test.local",
        approved=True,
    )
    result = orchestrator.run_task(task)

    session_path = tmp_path / session_id

    assert saved_findings[0]["session_id"] == session_id
    assert saved_findings[0]["task_id"] == task.id
    assert saved_findings[0]["tool_run_id"] == 99
    assert result["status"] == "completed"
    assert result["tool_card"]["key"] == "run_nmap"
    assert result["tool_card"]["approval_class"] == "explicit_approval"
    assert result["parsed_result"]["host"] == "test.local"
    assert result["next_steps"] == ["run_http_probe"]

    assert (session_path / "nmap_stdout.txt").exists()
    assert (session_path / "nmap_stderr.txt").exists()
    assert (session_path / "report.md").exists()
    assert (session_path / "events.jsonl").exists()

    assert (session_path / "nmap_stdout.txt").read_text(encoding="utf-8") == tool.result["stdout"]
    assert (session_path / "report.md").read_text(encoding="utf-8") == "# Success Report\n\nAll good."

    assert tool.called_with == "test.local"
    assert len(saved_tool_runs) == 1
    assert len(saved_findings) == 1
    assert len(saved_memory) == 1

def test_orchestrator_returns_tool_error_on_nonzero_returncode(monkeypatch, tmp_path):
    _patch_common(monkeypatch, tmp_path)

    orchestrator = Orchestrator()
    orchestrator.aether = DummyAether(action="run_nmap")

    monkeypatch.setattr(
        orchestrator_module,
        "validate_single_target",
        lambda target: ScopeCheckResult(True, "10.0.0.9", "Valid single IP target."),
    )

    tool = DummyTool(
        {
            "tool": "nmap",
            "command": "nmap -Pn -sV 10.0.0.9",
            "stdout": "",
            "stderr": "nmap execution failed",
            "returncode": 2,
        }
    )
    monkeypatch.setitem(orchestrator_module.TOOL_REGISTRY, "run_nmap", _tool_entry(tool))

    session_id = "session-tool-error"
    result = orchestrator.run_task(
        Task(
            session_id=session_id,
            objective="scan 10.0.0.9",
            target="10.0.0.9",
            approved=True,
        )
    )

    session_path = tmp_path / session_id

    assert result["status"] == "tool_error"
    assert result["message"] == "Tool execution failed."
    assert result["tool_card"]["key"] == "run_nmap"
    assert result["raw_result"]["returncode"] == 2

    assert (session_path / "nmap_stdout.txt").exists()
    assert (session_path / "nmap_stderr.txt").exists()
    assert (session_path / "events.jsonl").exists()
    assert not (session_path / "report.md").exists()