from __future__ import annotations

from pathlib import Path

import app.core.orchestrator as orchestrator_module
from app.core.orchestrator import Orchestrator
from app.core.scope import ScopeCheckResult
from app.schemas.tasks import Task
from app.tools.tool_cards import ToolArgument, ToolCard, ToolRegistration


class DummyAether:
    def classify_task(self, objective: str) -> str:
        return "recon"

    def plan(self, task: Task) -> dict:
        return {
            "agent": "AETHER",
            "action": "run_nmap",
            "reason": "dispatch test",
        }


class DummyScribe:
    def generate_markdown_report(self, session_id: str, objective: str, parsed_output: dict) -> str:
        return "# Dispatch Report\n\nGenerated by test."


class DummyWatcher:
    def process(self, session_id: str, parsed_output: dict, previous_memory: dict | None = None) -> dict:
        return {
            "agent": "WATCHER",
            "observations": ["Host: dispatch.local"],
            "unresolved": [],
            "suggestions": ["run_http_probe"],
            "tags": ["service:http"],
            "summary": "HTTP detected.",
            "priority": "medium",
        }


class DummyTool:
    def __init__(self) -> None:
        self.called_with: str | None = None

    def run(self, target: str) -> dict:
        self.called_with = target
        return {
            "tool": "nmap",
            "command": "nmap -Pn -sV dispatch.local",
            "stdout": "Nmap scan report for dispatch.local\nHost is up.\n80/tcp open http nginx 1.24.0\n",
            "stderr": "",
            "returncode": 0,
        }


def _session_path_factory(tmp_path: Path):
    def _get_session_path(session_id: str) -> Path:
        path = tmp_path / session_id
        path.mkdir(parents=True, exist_ok=True)
        return path
    return _get_session_path


def test_orchestrator_dispatches_through_registered_tool_path(monkeypatch, tmp_path):
    orchestrator = Orchestrator()
    orchestrator.aether = DummyAether()
    orchestrator.scribe = DummyScribe()
    orchestrator.watcher = DummyWatcher()

    dummy_tool = DummyTool()

    tool_entry = ToolRegistration(
        card=ToolCard(
            key="run_nmap",
            display_name="Nmap Service Scan",
            summary="Dispatch test tool.",
            approval_class="explicit_approval",
            scope_rule="single_target",
            allowed_categories=("recon",),
            arguments=(
                ToolArgument(
                    name="target",
                    kind="target",
                    required=True,
                    description="Single target",
                ),
            ),
            artifacts=("nmap_stdout.txt", "nmap_stderr.txt"),
            common_followups=("run_http_probe",),
            failure_modes=("nonzero_returncode",),
            operator_notes="Dispatch regression test.",
        ),
        tool=dummy_tool,
        parser=orchestrator_module.parse_nmap_output,
        stores_findings=True,
        generates_report=True,
        uses_watcher=True,
    )

    monkeypatch.setattr(orchestrator_module, "get_session_path", _session_path_factory(tmp_path))
    monkeypatch.setattr(orchestrator_module, "save_task", lambda task: None)
    monkeypatch.setattr(orchestrator_module, "save_tool_run", lambda **kwargs: 42)
    monkeypatch.setattr(
        orchestrator_module,
        "save_findings",
        lambda session_id, parsed_output, task_id=None, tool_run_id=None: None,
    )
    monkeypatch.setattr(orchestrator_module, "save_session_memory", lambda session_id, data: None)
    monkeypatch.setattr(orchestrator_module, "get_session_memory", lambda session_id: None)
    monkeypatch.setattr(
        orchestrator_module,
        "validate_single_target",
        lambda target: ScopeCheckResult(True, "dispatch.local", "Valid hostname target."),
    )
    monkeypatch.setattr(
        orchestrator_module,
        "parse_nmap_output",
        lambda output: {
            "host": "dispatch.local",
            "host_status": "up",
            "filtered_summary": None,
            "closed_summary": None,
            "open_ports": [80],
            "services": ["http"],
            "port_details": [
                {
                    "port": 80,
                    "protocol": "tcp",
                    "state": "open",
                    "service": "http",
                    "version": "nginx 1.24.0",
                }
            ],
            "os_hint": "Linux",
            "scan_protocols_seen": ["tcp"],
            "all_port_states": {"open": 1},
            "evidence_count": 1,
        },
    )
    monkeypatch.setitem(orchestrator_module.TOOL_REGISTRY, "run_nmap", tool_entry)

    called = {"value": False}
    real_execute = orchestrator._execute_registered_tool

    def wrapped_execute(task, plan, tool_entry, session_path, log_path):
        called["value"] = True
        return real_execute(task, plan, tool_entry, session_path, log_path)

    monkeypatch.setattr(orchestrator, "_execute_registered_tool", wrapped_execute)

    task = Task(
        session_id="dispatch-session",
        objective="scan dispatch.local",
        target="dispatch.local",
        approved=True,
    )

    result = orchestrator.run_task(task)

    session_path = tmp_path / "dispatch-session"

    assert called["value"] is True
    assert result["status"] == "completed"
    assert result["tool_card"]["key"] == "run_nmap"
    assert result["parsed_result"]["host"] == "dispatch.local"
    assert result["next_steps"] == ["run_http_probe"]
    assert dummy_tool.called_with == "dispatch.local"
    assert (session_path / "nmap_stdout.txt").exists()
    assert (session_path / "nmap_stderr.txt").exists()
    assert (session_path / "report.md").exists()
    assert (session_path / "events.jsonl").exists()